[package]
name = "deUSD"
edition = "2024.beta"

[addresses]
elixir = "0x0"
initial_rewarder = "_"

# Addresses for testing purposes
test_coin = "0xccc"

[dev-addresses]
initial_rewarder = "0xabc"

[dependencies]

[dev-dependencies]
